---
## NFS specific


######################### Install Basic Packages

  - name: Install nfs Packages
    gather_facts: False
    include: ./packages.yml
    tags: [  install_nfs_packages ]


######################### Config NFS Mount Storage

  - name: config_nfs_mount_storage
    gather_facts: False
    include: ./config_nfs_mount_storage.yml
    tags: [  config_nfs_mount_storage ]
