######################### env-specific specific
- name: Include vars and secret vars
  hosts: localhost
  connection: local
  tasks:
  vars_files:
    - "./{{ config_name }}_vars.yml"
    - "./{{ config_name }}_secret_vars.yml"


- name: Change Environment Hostnames
  hosts: localhost
  become: yes
  vars_files:
    - "./{{ config_name }}_vars.yml"
  tags: [ env-specific, change_internal_hostnames ]
  tasks:
  - name: Change hostnames
    shell: "ansible all  -i /tmp/hosts-{{ config_name }}-{{guid}} -m shell -a 'sudo hostnamectl set-hostname {{ '{{'  }} openshift_hostname {{ '}}' }} '"



- name: Change Environment Hostnames
  hosts: bastions
  become: yes
  vars_files:
    - "./{{ config_name }}_vars.yml"
  tasks:
  - hostname:
      name: "bastion.{{guid}}.openshift.opentlc.com"

