  - name: install docker
    yum: name="docker-{{ docker_version }}" state=present

  - name: lock docker version
    command: yum versionlock add "docker*"

  - name: generate docker-storage-setup config
    template: src=./sysconfig.docker-storage-setup.j2 dest=/etc/sysconfig/docker-storage-setup

  - name: start and enable docker
    service: name=docker state=started enabled=yes
