- name: Starting environment deployment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - "../Environments/{{config}}_vars.yml"
  tasks:

######################### Generate CF Template
######################### Launch CF Template


  - name: Provisioning Environment
    gather_facts: False
    vars_files:
    - "../Environments/{{config}}_vars.yml"
    include: ./provision_cf.yml
    tags: [ provisioning, gen_cf_templatem, provisiong_cf_template ]



######################### Populate Dynamic Inventory

  - name: Provisioning Environment
    gather_facts: False
    vars_files:
    - "../Environments/{{config}}_vars.yml"
    include: ./dynamic_inventory.yml
    tags: [ dynamic_inventory, get_hosts, populate_hosts, generate_ansible_host_file ]

######################### LOCAL Bastion Proxy Config

  - name: Generate ssh.cfg Template
    template: src=files/ssh.cfg.j2 dest=../workdir/ssh-{{config}}-{{guid}}.cfg
    tags: [ bastion_proxy_config, create_ssh_cfg_template ]

  - name: copy ssh.cfg into local ~.ssh/Config
    shell: "cat ../workdir/ssh-{{config}}-{{guid}}.cfg >> ~/.ssh/config"
    tags: [ bastion_proxy_config, workaround, config_ssh_config_file]


######################### Run COMMON Tasks on all hosts

- name: Configuring common Hosts
  hosts: bastions,nfs,masters,infranodes,nodes
  become: yes
  vars_files:
    - "../Environments/{{config}}_vars.yml"
  roles:
    - common
  tags: [ common_tasks ]


######################### Run bastion Tasks



- name: Configuring Bastion Hosts
  hosts: bastions
  become: yes
  vars_files:
    - "../Environments/{{config}}_vars.yml"
  roles:
    - bastion
  tags: [ bastion_tasks ]


#########################Configuring nfs Host

- name: Configuring nfs Host
  hosts: nfs
  become: yes
  vars_files:
    - "../Environments/{{config}}_vars.yml"
  roles:
    - nfs
  tags: [ nfs_tasks ]

####################### Startring OpenShift Specific Deployment

#########################Configuring openshfit-provisioner

- name: Configuring openshfit-provisioner
  hosts: bastions
  become: yes
  vars_files:
    - "../Environments/{{config}}_vars.yml"
  roles:
    - openshift-provisioner


#########################Configuring openshfit-nodes

- name: Configuring openshfit-nodes
  hosts: infranodes,nodes
  become: yes
  vars_files:
    - "../Environments/{{config}}_vars.yml"
  roles:
    - openshift-node
  tags: [ openshift_node_tasks ]
