# ######################## Generate CF Template
# - name: Generate CloudFormation Template
#  template: src=files/cf_templates/cf.{{ config_name }}.template.j2 dest=/tmp/cf.{{ config_name }}.{{ guid }}.json
#  tags: [ provisioning, gen_cf_template]
#
# ## This part is temporary until we consolidate file structure into Environments/{{ config_name }}
#

## Backward compatability for bu-workshop

# - name: Generate CloudFormation Template from old location
#   template: src=files/cf_templates/cf.{{ config_name }}.template.j2 dest=/tmp/cf.{{ config_name }}.{{ guid }}.json
#   ignore_errors: true
#
#   tags: [ provisioning, gen_cf_template]

## New method for Environments/{{ config_name }} file structure


- name: Generate CloudFormation Template from  the new location
  template:
    src: ../configs/standard_configs/{{ config_name }}/files/cf.{{ config_name }}.template.j2
    dest: /tmp/cf.{{ config_name }}.{{ guid }}.json
  ignore_errors: true
  tags:
    - provisioning
    - gen_cf_template

######################### Launch CF Template
- name: Launch CloudFormation template
  cloudformation:
    stack_name: "{{ project_tag }}"
    state: "present"
    region: "{{ aws_region }}"
    disable_rollback: false
    template: "/tmp/cf.{{ config_name }}.{{ guid }}.json"
    tags:
      Stack: "project {{ project_tag }}"
  tags:
    - provisioning
    - provision_cf_template
  register: cloudformation_out

- name: Store S3 Bucket ID
  set_fact:
    s3_bucket: "{{ cloudformation_out.stack_outputs.RegistryS3Output }}"

- debug:
    msg: "bucket is {{ s3_bucket }}"

- name: Store internal route53 ID
  set_fact:
    internal_zone_id: "{{ cloudformation_out.stack_outputs.Route53internalzoneOutput }}"

- name: debug internal dns zone id
  debug:
    var: internal_zone_id
