- name: Starting environment deployment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - "../configs/{{ config_name }}_vars.yml"
  - "../configs/{{ config_name }}_secret_vars.yml"
  tasks:

  - name: Creating Dynamic Inventory
    gather_facts: False
    vars_files:
    - "../configs/{{ config_name }}_vars.yml"
    - "../configs/{{ config_name }}_secret_vars.yml"
    include: ./dynamic_inventory.yml
    tags: [ dynamic_inventory, get_hosts, populate_hosts, generate_ansible_host_file ]
## TODO: Template this
  - name: Added Bastion Proxy to local ~/.ssh/config file
    blockinfile:
      dest: ~/.ssh/config1
      marker: "##### {mark} ADDED BASTION PROXY HOST {{hostvars[groups['bastions'][0]]['public_hostname']}} {{ config_name }}-{{ guid }} ######"
      content: |
          Host {{hostvars[groups['bastions'][0]]['public_hostname']}}
            Hostname {{hostvars[groups['bastions'][0]]['public_hostname']}}
            ForwardAgent yes
            IdentityFile ~/.ssh/{{key_name}}.pem
            IdentitiesOnly yes
            User ec2-user
            ControlMaster auto
            ControlPath /tmp/{{project_tag}}--%r@%h:%p
            ControlPersist 5m
            ForwardAgent yes
            StrictHostKeyChecking no

  - debug: msg={{ item }}
    with_items: "{{ groups['all'] }}"

## TODO: Template this
  - name: Add all hosts to local  ~/.ssh/config file
    blockinfile:
      dest: ~/.ssh/config1
      marker: "##### {mark} ADDED Node Proxy Config  {{ item }} {{ config_name }}-{{ guid }} ######"
      block: |
          Host {{ item }}
            Hostname {{ item }}
            User ec2-user
            IdentityFile {{hostvars[groups['bastions'][0]]['ansible_ssh_private_key_file']}}
            ProxyCommand ssh {{hostvars[groups['bastions'][0]]['public_hostname']}} -W %h:%p
            ForwardAgent yes
            StrictHostKeyChecking no
    with_items: groups['allhosts']
